### ISSUE TITLE
ESP32 Drive with C++ node from PC over Wifi

### ISSUE THREAD

**Issue by noshluk2** [Robotisim/mobile_robotics_ROS2#23]
- Make esp32 subscribe cmd_vel topic of geometric_msgs/Twist type
- use telop twist keyboard to drive robot running from pc

**Comment by ibrahimmansur4** [comment]
do the steps told in #18 for serial setup. 
keep in mind in step 8 to change the name of project from pingpong to the folder name with which you saved.
After source installation step check the topic list with : ros2 topic list 
Then run the keyboard : ros2 run teleop_twist_keyboard teleop_twist_keyboard 
And in another terminal :  ros2 topic echo /cmd_vel

**Comment by ibrahimmansur4** [comment]
Code taken from this repo : https://github.com/Reinbert/ros_esp32cam_diffdrive
Video found for udp setup : https://www.youtube.com/watch?v=RdbH1-_UMBQ&t=204s

**Comment by ibrahimmansur4** [comment]
was not able to build the package after some updates

![Image](https://github.com/Robotisim/mobile_robotics_ROS2/assets/81290322/3cbc0b8c-31a3-4b80-8f4d-18bbcc2598ee)

**Comment by ibrahimmansur4** [comment]
/opt/ros/humble/lib$ sudo ln -s libfastrtps.so.2.6.6 libfastrtps.so.2.6.5
the required file was updated to a newer version.
had to link the new file to old one to resolve issue

**Comment by ibrahimmansur4** [comment]
now setup of micro ros not required.using platform.io  code can be written in cpp and other header files can be automatically intergated. the build and flash steps not required manually. esp idf can do it.
after uploading micro ros code to esp on the terminal start the communication on the port only.

**Comment by ibrahimmansur4** [comment]
https://github.com/micro-ROS/micro_ros_platformio

dependency for micro ros in platformio
